{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-testing-manifest",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.6.1.aar",
          "url": "fragment-testing-manifest-1.6.1.aar",
          "size": 18877,
          "sha512": "02f6ee4602008e67e99ff1f0928ededc3209fc9a53874d5bbecfa8526878a7364bdde6b0ac5ac5d7b853fb96bee2124e65e27b2689138e5ddd5a12924b4c0df2",
          "sha256": "185dc939a78d2f500188b20a7327e55b28cad7e4b944a73b3396d7ff89bc579c",
          "sha1": "64174461f11a028595558bfa1b5a4d072e335499",
          "md5": "3cfc9025f3e8db32f28645559d6c41b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.6.1.aar",
          "url": "fragment-testing-manifest-1.6.1.aar",
          "size": 18877,
          "sha512": "02f6ee4602008e67e99ff1f0928ededc3209fc9a53874d5bbecfa8526878a7364bdde6b0ac5ac5d7b853fb96bee2124e65e27b2689138e5ddd5a12924b4c0df2",
          "sha256": "185dc939a78d2f500188b20a7327e55b28cad7e4b944a73b3396d7ff89bc579c",
          "sha1": "64174461f11a028595558bfa1b5a4d072e335499",
          "md5": "3cfc9025f3e8db32f28645559d6c41b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.6.1-sources.jar",
          "url": "fragment-testing-manifest-1.6.1-sources.jar",
          "size": 2869,
          "sha512": "f3566649d0bee9053bc1203bbdc95b95b11ba7ecb49cd8aef4e0c659a9abd64e027bf8e3077969bcbc04a1393276f40f03e7445ff2db52359594ebda6e2177ac",
          "sha256": "73b198ac57d5767a9a7ab60da12a83128b1ed91fe3902874ecf8bed34d994546",
          "sha1": "9f26b801b4abf49b5cd2fe81cee1ee68591f9f00",
          "md5": "ee4c5fc1413d0a275da62a3b38b71c78"
        }
      ]
    }
  ]
}