{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "shadowapi",
    "version": "4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        }
      ],
      "files": [
        {
          "name": "shadowapi-4.9.jar",
          "url": "shadowapi-4.9.jar",
          "size": 16071,
          "sha512": "57ad810ff224fdfc2c9033b9b0b43825979f9a5843ff2f3d553c02e722aa27a3cab851d0ba93e1433337535344b1cd356ddea5b86bcbe75c77b01a2901e793bf",
          "sha256": "8ed30f020b3301730d80245ac0fa530837ea0a4d7f6c8b4e127a4150705afeda",
          "sha1": "1cc100f3bbff187c9b6e7055dc733f582cb4df64",
          "md5": "3012831f3c0e02dc7401a1af96964516"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        }
      ],
      "files": [
        {
          "name": "shadowapi-4.9.jar",
          "url": "shadowapi-4.9.jar",
          "size": 16071,
          "sha512": "57ad810ff224fdfc2c9033b9b0b43825979f9a5843ff2f3d553c02e722aa27a3cab851d0ba93e1433337535344b1cd356ddea5b86bcbe75c77b01a2901e793bf",
          "sha256": "8ed30f020b3301730d80245ac0fa530837ea0a4d7f6c8b4e127a4150705afeda",
          "sha1": "1cc100f3bbff187c9b6e7055dc733f582cb4df64",
          "md5": "3012831f3c0e02dc7401a1af96964516"
        }
      ]
    }
  ]
}
