{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-testing-manifest",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.6.2.aar",
          "url": "fragment-testing-manifest-1.6.2.aar",
          "size": 18875,
          "sha512": "42261187122ab480ba7dd63d42692098408c24f681faf5de3e65ab2e52b8f335df93d7bedd438ce5821ee4fdd955c23f0b427258e16e3c2ea525c6d2a3fa9a69",
          "sha256": "a9c3bf8cad2abc920b1e00011a9d93a7aa3753a8ffae8d06c7dcf5dfac56090d",
          "sha1": "31ff51cabdd14693e27cb7139e9f37441d4e22e0",
          "md5": "4545e036c2f3a7e9d2809cc3fbda6ab9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.6.2.aar",
          "url": "fragment-testing-manifest-1.6.2.aar",
          "size": 18875,
          "sha512": "42261187122ab480ba7dd63d42692098408c24f681faf5de3e65ab2e52b8f335df93d7bedd438ce5821ee4fdd955c23f0b427258e16e3c2ea525c6d2a3fa9a69",
          "sha256": "a9c3bf8cad2abc920b1e00011a9d93a7aa3753a8ffae8d06c7dcf5dfac56090d",
          "sha1": "31ff51cabdd14693e27cb7139e9f37441d4e22e0",
          "md5": "4545e036c2f3a7e9d2809cc3fbda6ab9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.6.2-sources.jar",
          "url": "fragment-testing-manifest-1.6.2-sources.jar",
          "size": 2869,
          "sha512": "f3566649d0bee9053bc1203bbdc95b95b11ba7ecb49cd8aef4e0c659a9abd64e027bf8e3077969bcbc04a1393276f40f03e7445ff2db52359594ebda6e2177ac",
          "sha256": "73b198ac57d5767a9a7ab60da12a83128b1ed91fe3902874ecf8bed34d994546",
          "sha1": "9f26b801b4abf49b5cd2fe81cee1ee68591f9f00",
          "md5": "ee4c5fc1413d0a275da62a3b38b71c78"
        }
      ]
    }
  ]
}