{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation-experimental",
    "version": "1.1.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7163140"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotation-experimental-1.1.0-rc01.aar",
          "url": "annotation-experimental-1.1.0-rc01.aar",
          "size": 17197,
          "sha512": "f8de137f9f58528d2cd6ed30ebc7e022e84c0926f12767a76251261945bf00461672f2d26aab518181402d76700960432e29e7701507464e21bb01a10054167e",
          "sha256": "afde29eec0cbef54bb97af487678fdc6f4e51c7acd38d9ea5ff699730fa3f2c8",
          "sha1": "182ad07bb9a04f0a1a8988a5960b167aa526c543",
          "md5": "75dea331063365bb95ade01250642129"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.1.0-rc01.aar",
          "url": "annotation-experimental-1.1.0-rc01.aar",
          "size": 17197,
          "sha512": "f8de137f9f58528d2cd6ed30ebc7e022e84c0926f12767a76251261945bf00461672f2d26aab518181402d76700960432e29e7701507464e21bb01a10054167e",
          "sha256": "afde29eec0cbef54bb97af487678fdc6f4e51c7acd38d9ea5ff699730fa3f2c8",
          "sha1": "182ad07bb9a04f0a1a8988a5960b167aa526c543",
          "md5": "75dea331063365bb95ade01250642129"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.1.0-rc01-sources.jar",
          "url": "annotation-experimental-1.1.0-rc01-sources.jar",
          "size": 5310,
          "sha512": "24d5b9245f60fc2b8b321e49743b4196dec130e42a83ca6a880353f78070d1772e64a3baae6cfef73f3e5616c803c7461eeb4833c4f9b48f56536c113fcfbe99",
          "sha256": "7ea8c98ebd649ee4c0a74b19e1e81ac5f4469be5a12555f288083f1efd4f29d9",
          "sha1": "238eb640abf1ca6c952c7cd2e9423fe7f715713f",
          "md5": "05d975aadee90454e8e41c039e3895ed"
        }
      ]
    }
  ]
}
