{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "resources",
    "version": "4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "pluginapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "resources-4.9.jar",
          "url": "resources-4.9.jar",
          "size": 396176,
          "sha512": "c46288e9fe68aa299fed316a03c4741da460f8250ba7cef7656391728a4622022fa57f98889d24408c752d0dac35025880367a783c4be8a463f49ebc85ced214",
          "sha256": "1555494498e66edcee4e58e448ddc9faf7e8aaf7b36ee16e3446ad8818aad1c6",
          "sha1": "18388d81fc12e78501f2e48972747a61c249590b",
          "md5": "09fe4c329a63f0917ea54b8f8732dc2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "pluginapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "resources-4.9.jar",
          "url": "resources-4.9.jar",
          "size": 396176,
          "sha512": "c46288e9fe68aa299fed316a03c4741da460f8250ba7cef7656391728a4622022fa57f98889d24408c752d0dac35025880367a783c4be8a463f49ebc85ced214",
          "sha256": "1555494498e66edcee4e58e448ddc9faf7e8aaf7b36ee16e3446ad8818aad1c6",
          "sha1": "18388d81fc12e78501f2e48972747a61c249590b",
          "md5": "09fe4c329a63f0917ea54b8f8732dc2b"
        }
      ]
    }
  ]
}
