{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-testing",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.6.2.aar",
          "url": "fragment-testing-1.6.2.aar",
          "size": 27063,
          "sha512": "3919e6c21f6da3d2f080bb474f4c6760b6c097348c3d8c86bd4a02461082e4729d2b5f981e826d0901cca104a184ffdd0c5688db9dd217354f207b080e48cbab",
          "sha256": "4b2269953b6d61d622b51c1d661a63f0709e7db97abeafe621acbd1ecc8c7228",
          "sha1": "b0ca2c65de2ef366f35b972cbfe780b06add0733",
          "md5": "daaea8fcc0e37c97907528ac701b6bc0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.6.2.aar",
          "url": "fragment-testing-1.6.2.aar",
          "size": 27063,
          "sha512": "3919e6c21f6da3d2f080bb474f4c6760b6c097348c3d8c86bd4a02461082e4729d2b5f981e826d0901cca104a184ffdd0c5688db9dd217354f207b080e48cbab",
          "sha256": "4b2269953b6d61d622b51c1d661a63f0709e7db97abeafe621acbd1ecc8c7228",
          "sha1": "b0ca2c65de2ef366f35b972cbfe780b06add0733",
          "md5": "daaea8fcc0e37c97907528ac701b6bc0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.6.2-sources.jar",
          "url": "fragment-testing-1.6.2-sources.jar",
          "size": 4658,
          "sha512": "3aa27b26eedd094a73a21adc10b9c975bd03c105fae4f6df1445cda82cc6e86bc29ab831a5d9cb1d16e829bd955671d24811296cc5ab3ab0dbc855c97e8652ed",
          "sha256": "56ff5da8ed3dd3d0df87a771abe3d0180122fcf63b7dec9ea05331a22f07c5fb",
          "sha1": "ac3d30383a35e2c1b00c572f087a045c48a5a3bd",
          "md5": "5d842ee9c3d5781dda0049df941e88f1"
        }
      ]
    }
  ]
}