{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "nativeruntime",
    "version": "4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "nativeruntime-4.9.jar",
          "url": "nativeruntime-4.9.jar",
          "size": 38685149,
          "sha512": "e8a9bed56b10fddd973bc6637b197e8d360cad36bd9d90541dae6b416efd52cb360cf5a5edd044fcc9ddcb8d9b7e6d1584c1baa2970a507008ce5d9dd40a7bbb",
          "sha256": "f52db26d76d93bb764bff637aab16f55d03b3206604592a61f14ceb727c4d369",
          "sha1": "2e5c099e4bc1b9f7dacb359b9b62d0b1bcc1ca7e",
          "md5": "f8c51933dc0eca290119707cf58c6d1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "nativeruntime-4.9.jar",
          "url": "nativeruntime-4.9.jar",
          "size": 38685149,
          "sha512": "e8a9bed56b10fddd973bc6637b197e8d360cad36bd9d90541dae6b416efd52cb360cf5a5edd044fcc9ddcb8d9b7e6d1584c1baa2970a507008ce5d9dd40a7bbb",
          "sha256": "f52db26d76d93bb764bff637aab16f55d03b3206604592a61f14ceb727c4d369",
          "sha1": "2e5c099e4bc1b9f7dacb359b9b62d0b1bcc1ca7e",
          "md5": "f8c51933dc0eca290119707cf58c6d1e"
        }
      ]
    }
  ]
}
