{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "shadows-framework",
    "version": "4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "nativeruntime",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "resources",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "pluginapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "sandbox",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadowapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils-reflector",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "monitor",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.almworks.sqlite4java",
          "module": "sqlite4java",
          "version": {
            "requires": "1.0.392"
          }
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "70.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.9"
          }
        }
      ],
      "files": [
        {
          "name": "shadows-framework-4.9.jar",
          "url": "shadows-framework-4.9.jar",
          "size": 4253448,
          "sha512": "12f4c53ffabb2fa67505bef60ad9545a5d0f68e68caf04ef6b625fde515c47694dacc92ddf130bf6827b1da6ba9692da5d6c68a04ac18435a3d6b4cb8a42b966",
          "sha256": "73c5e453f33ee6f44143bcf4c76ed55c0991e7bd7f64c06db3779f9540799ab8",
          "sha1": "8fbebe0a9756c24302efe02be6c65ef988cca612",
          "md5": "cca539fe16d7b963165d0bfcb46fa199"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "nativeruntime",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "resources",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "pluginapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "sandbox",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadowapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils-reflector",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "monitor",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.almworks.sqlite4java",
          "module": "sqlite4java",
          "version": {
            "requires": "1.0.392"
          }
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "70.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.9"
          }
        }
      ],
      "files": [
        {
          "name": "shadows-framework-4.9.jar",
          "url": "shadows-framework-4.9.jar",
          "size": 4253448,
          "sha512": "12f4c53ffabb2fa67505bef60ad9545a5d0f68e68caf04ef6b625fde515c47694dacc92ddf130bf6827b1da6ba9692da5d6c68a04ac18435a3d6b4cb8a42b966",
          "sha256": "73c5e453f33ee6f44143bcf4c76ed55c0991e7bd7f64c06db3779f9540799ab8",
          "sha1": "8fbebe0a9756c24302efe02be6c65ef988cca612",
          "md5": "cca539fe16d7b963165d0bfcb46fa199"
        }
      ]
    }
  ]
}
