{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "pluginapi",
    "version": "4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "pluginapi-4.9.jar",
          "url": "pluginapi-4.9.jar",
          "size": 10258,
          "sha512": "548997ee91f113308f26ad1844439fb5a5a737d783c241bc88297c5cfcd0422c97d5ab133630b862e8736cd1ab9ebd5612c13f40b8cbf1c32883015ab5a0a5d1",
          "sha256": "7bf7780d0782a9bd3d1e15bdef8c331f90a3d3cbfbd9dba9d7ac780716d56107",
          "sha1": "0523694e9cbb4284db50d5ae74412273d86696f2",
          "md5": "523e19fee26c46cc85d8a1d3941f5206"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "pluginapi-4.9.jar",
          "url": "pluginapi-4.9.jar",
          "size": 10258,
          "sha512": "548997ee91f113308f26ad1844439fb5a5a737d783c241bc88297c5cfcd0422c97d5ab133630b862e8736cd1ab9ebd5612c13f40b8cbf1c32883015ab5a0a5d1",
          "sha256": "7bf7780d0782a9bd3d1e15bdef8c331f90a3d3cbfbd9dba9d7ac780716d56107",
          "sha1": "0523694e9cbb4284db50d5ae74412273d86696f2",
          "md5": "523e19fee26c46cc85d8a1d3941f5206"
        }
      ]
    }
  ]
}
