{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "robolectric",
    "version": "4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "junit",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "pluginapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "resources",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "sandbox",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils-reflector",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "plugins-maven-dependency-resolver",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-framework",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        }
      ],
      "files": [
        {
          "name": "robolectric-4.9.jar",
          "url": "robolectric-4.9.jar",
          "size": 167030,
          "sha512": "be46ffce0853b8d820cf471d690c4eae8fca3101065a05a931b2ea4c69840f068f517dfb4d92eb86f0cba1645259338bced3c98819e3e795f1183085b9be917d",
          "sha256": "6f8eabf2dc1b09b8ef01946ef416b9b7f923b4fb33be5886a6690b4e5878866a",
          "sha1": "927a6ff67373a944923eee1f1e8b89847e8a6316",
          "md5": "26d80133b7f11bb0c380a9cf4da7f4c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.conscrypt",
          "module": "conscrypt-openjdk-uber",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-idling-resource",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "junit",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "pluginapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "resources",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "sandbox",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils-reflector",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "plugins-maven-dependency-resolver",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadows-framework",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        }
      ],
      "files": [
        {
          "name": "robolectric-4.9.jar",
          "url": "robolectric-4.9.jar",
          "size": 167030,
          "sha512": "be46ffce0853b8d820cf471d690c4eae8fca3101065a05a931b2ea4c69840f068f517dfb4d92eb86f0cba1645259338bced3c98819e3e795f1183085b9be917d",
          "sha256": "6f8eabf2dc1b09b8ef01946ef416b9b7f923b4fb33be5886a6690b4e5878866a",
          "sha1": "927a6ff67373a944923eee1f1e8b89847e8a6316",
          "md5": "26d80133b7f11bb0c380a9cf4da7f4c5"
        }
      ]
    }
  ]
}
