{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "okhttp",
    "version": "4.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3ep7d6whxbagljmjliudfrxccy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-4.9.1.jar",
          "url": "okhttp-4.9.1.jar",
          "size": 791390,
          "sha512": "b09c59af3bde102c1d727d14f8c6f2455deac69c30ea458681c1f1feba4e374c485bca56115e50feb719b816e158a3b548d81579207f14e7de6e297d24e7155a",
          "sha256": "6afdd8f35f4eb60df965c290fa3acf29443fa986545113d0729b8461f6571f8f",
          "sha1": "51215279c3fe472c59b6b7dd7491e6ac2e28a81b",
          "md5": "018ce5d28ab7958a1f0bb93b35215ef6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-4.9.1.jar",
          "url": "okhttp-4.9.1.jar",
          "size": 791390,
          "sha512": "b09c59af3bde102c1d727d14f8c6f2455deac69c30ea458681c1f1feba4e374c485bca56115e50feb719b816e158a3b548d81579207f14e7de6e297d24e7155a",
          "sha256": "6afdd8f35f4eb60df965c290fa3acf29443fa986545113d0729b8461f6571f8f",
          "sha1": "51215279c3fe472c59b6b7dd7491e6ac2e28a81b",
          "md5": "018ce5d28ab7958a1f0bb93b35215ef6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-4.9.1-javadoc.jar",
          "url": "okhttp-4.9.1-javadoc.jar",
          "size": 261,
          "sha512": "58aad817ea2d9f575f0a9714459c153890d5938b5248524a0706fae086e465139d912283f805a666d9689d7822fddc17b3f02af7786c5cfc809be461049a1b83",
          "sha256": "2254cd706b28792df9605d60451bc923aa82dc6eeadc339011779925d4bb116e",
          "sha1": "03c040ed46a86d587b8e1926d73d31d150cf547b",
          "md5": "45a2691895b88497cf92dc4b82e148a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-4.9.1-sources.jar",
          "url": "okhttp-4.9.1-sources.jar",
          "size": 363242,
          "sha512": "27dd76711e056fb9a947b334562630bde31dbcb611836def44a5a6ec00b959294b3669bdcb036f5f2a4e6a2a0a14f8f48172c995b4065ba75886c9773ed88cfc",
          "sha256": "5d1204506ad077509f133fcc865fecf5319f42a063bc6a3e5447b3e5ae971080",
          "sha1": "2708191169cdea968661617776a64eb336f86bbd",
          "md5": "e8728978c1c664eab4b330de7be045c9"
        }
      ]
    }
  ]
}
