{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "logging-interceptor",
    "version": "4.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3ep7d6whxbagljmjliudfrxccy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-interceptor-4.9.1.jar",
          "url": "logging-interceptor-4.9.1.jar",
          "size": 15680,
          "sha512": "38001983699439caac7f57ce577e72fe70f103686528f3df64a975e045836f5a2d167d349fff93d100d1b4971e3cbe9982fd48df9a2df623d3556a3a69d5d056",
          "sha256": "08ae52d4e7ab4dde8f94970bbeb1545b51934d4b3f0802f6e816b0522902fa9d",
          "sha1": "00e4c20c4ce426bc4df018b60e92e0362101b448",
          "md5": "b112b14223f5cf6668fbb315dde7a834"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "logging-interceptor-4.9.1.jar",
          "url": "logging-interceptor-4.9.1.jar",
          "size": 15680,
          "sha512": "38001983699439caac7f57ce577e72fe70f103686528f3df64a975e045836f5a2d167d349fff93d100d1b4971e3cbe9982fd48df9a2df623d3556a3a69d5d056",
          "sha256": "08ae52d4e7ab4dde8f94970bbeb1545b51934d4b3f0802f6e816b0522902fa9d",
          "sha1": "00e4c20c4ce426bc4df018b60e92e0362101b448",
          "md5": "b112b14223f5cf6668fbb315dde7a834"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-interceptor-4.9.1-javadoc.jar",
          "url": "logging-interceptor-4.9.1-javadoc.jar",
          "size": 261,
          "sha512": "fb4ac53bf73c7119618203f79d7608ae3e19c1821cc67efc7553f5e0c82a88ca80fa0c696e188ea36b93a9d89795a0cac7cf51d86f6b6d9ffae825e13ca1b697",
          "sha256": "63a7b814968bf17db275bed00d0a455884417c16ace25d4f575d01e94521636f",
          "sha1": "2000aab0ddc515c68aaea7466029efa09f0daf21",
          "md5": "fa0678fbb28d421211508c7caf801ef8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-interceptor-4.9.1-sources.jar",
          "url": "logging-interceptor-4.9.1-sources.jar",
          "size": 6003,
          "sha512": "912f04e74511a06ea3eac9ee8a2c0344e4482b077a4a8c447830489f35117f102123c052c5ef1e3ecfe28c8b8cdc45981f0245bdf70b43dcfde2720747ad7f41",
          "sha256": "89062920657b935f9d6f21665e37d2426968d4defc98812c67722604cd16ca93",
          "sha1": "99b675f700cc9d67abf7c27ecdec3561dbd11273",
          "md5": "fe492ca9f62ba121c7fde5035d161786"
        }
      ]
    }
  ]
}
