{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "utils-reflector",
    "version": "4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        }
      ],
      "files": [
        {
          "name": "utils-reflector-4.9.jar",
          "url": "utils-reflector-4.9.jar",
          "size": 22937,
          "sha512": "5c00bac13e4450cc3b5b89b76f1cffb5bc9ba2aee83adb2cdb5e87329789970fc3ee5684bbd051a85d2fc02c6cabae1ac9bc2333e9131d3e83d09aafe292d2df",
          "sha256": "e7034aed9a2343dbcb18a844c30a3904690176c39cbec9c9ce5f0c37062d95ee",
          "sha1": "382393ecae4e4e676d9c88081a77781a3ade283e",
          "md5": "55e919522adbb5f0a29f52fe772112a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        }
      ],
      "files": [
        {
          "name": "utils-reflector-4.9.jar",
          "url": "utils-reflector-4.9.jar",
          "size": 22937,
          "sha512": "5c00bac13e4450cc3b5b89b76f1cffb5bc9ba2aee83adb2cdb5e87329789970fc3ee5684bbd051a85d2fc02c6cabae1ac9bc2333e9131d3e83d09aafe292d2df",
          "sha256": "e7034aed9a2343dbcb18a844c30a3904690176c39cbec9c9ce5f0c37062d95ee",
          "sha1": "382393ecae4e4e676d9c88081a77781a3ade283e",
          "md5": "55e919522adbb5f0a29f52fe772112a8"
        }
      ]
    }
  ]
}
