{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-testing",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.6.1.aar",
          "url": "fragment-testing-1.6.1.aar",
          "size": 27062,
          "sha512": "2c001f66d3154c50fe397ef05da1db30add6a3165ab6387a594ef96d369d35810eb87bfd59e6bb1e7a06f136c45526cfbf8e1bbf482789e6e42d46ae7ebe6dd9",
          "sha256": "826e7ae51ba7133e905964b3d37ce8b2a4c7617ae6afa04295fb8dd06810807a",
          "sha1": "972e8072c16821959221d6264a7faec92c8cc514",
          "md5": "bb34d6a75eb8dcb237578b5086fa2516"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.6.1.aar",
          "url": "fragment-testing-1.6.1.aar",
          "size": 27062,
          "sha512": "2c001f66d3154c50fe397ef05da1db30add6a3165ab6387a594ef96d369d35810eb87bfd59e6bb1e7a06f136c45526cfbf8e1bbf482789e6e42d46ae7ebe6dd9",
          "sha256": "826e7ae51ba7133e905964b3d37ce8b2a4c7617ae6afa04295fb8dd06810807a",
          "sha1": "972e8072c16821959221d6264a7faec92c8cc514",
          "md5": "bb34d6a75eb8dcb237578b5086fa2516"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.6.1-sources.jar",
          "url": "fragment-testing-1.6.1-sources.jar",
          "size": 4658,
          "sha512": "3aa27b26eedd094a73a21adc10b9c975bd03c105fae4f6df1445cda82cc6e86bc29ab831a5d9cb1d16e829bd955671d24811296cc5ab3ab0dbc855c97e8652ed",
          "sha256": "56ff5da8ed3dd3d0df87a771abe3d0180122fcf63b7dec9ea05331a22f07c5fb",
          "sha1": "ac3d30383a35e2c1b00c572f087a045c48a5a3bd",
          "md5": "5d842ee9c3d5781dda0049df941e88f1"
        }
      ]
    }
  ]
}