{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "utils",
    "version": "4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "pluginapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "utils-4.9.jar",
          "url": "utils-4.9.jar",
          "size": 59253,
          "sha512": "e727b63d4ece3094f95cde41807d1eb2f5cf33c739c210181c4c3960b44e54d713e16d8419e540b3d72d40b5d5a89bcc73d097cf61c7a220852a6dbecb2abaf2",
          "sha256": "2b0293ee14281b6e9b14a262457e06f63906d87c9688d2e0549e0ada3fdc0b0a",
          "sha1": "61013713afe6fa1c4f0fd37092b710f5b9cf7e34",
          "md5": "85b522be1c8da83c487ac41fcb6526f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "pluginapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "utils-4.9.jar",
          "url": "utils-4.9.jar",
          "size": 59253,
          "sha512": "e727b63d4ece3094f95cde41807d1eb2f5cf33c739c210181c4c3960b44e54d713e16d8419e540b3d72d40b5d5a89bcc73d097cf61c7a220852a6dbecb2abaf2",
          "sha256": "2b0293ee14281b6e9b14a262457e06f63906d87c9688d2e0549e0ada3fdc0b0a",
          "sha1": "61013713afe6fa1c4f0fd37092b710f5b9cf7e34",
          "md5": "85b522be1c8da83c487ac41fcb6526f0"
        }
      ]
    }
  ]
}
