{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "sandbox",
    "version": "4.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadowapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils-reflector",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "sandbox-4.9.jar",
          "url": "sandbox-4.9.jar",
          "size": 129015,
          "sha512": "e84e0048a54141a0e9d15b4ba7e1c798b3c556e5394e86515fb4037e695a13d380e938aaa1fc3c2358c5ab78d164333c7b2963eec3922e701d2a01d93c80c142",
          "sha256": "2d1080e6f63012f0581c109b3547979ddd8cebd401f66ba9a746304720c5880d",
          "sha1": "2d7a214af08bffbca12b853201d5dc66587999b7",
          "md5": "949676c2f0fb9f592fa5709dfbfc315a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadowapi",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils-reflector",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "sandbox-4.9.jar",
          "url": "sandbox-4.9.jar",
          "size": 129015,
          "sha512": "e84e0048a54141a0e9d15b4ba7e1c798b3c556e5394e86515fb4037e695a13d380e938aaa1fc3c2358c5ab78d164333c7b2963eec3922e701d2a01d93c80c142",
          "sha256": "2d1080e6f63012f0581c109b3547979ddd8cebd401f66ba9a746304720c5880d",
          "sha1": "2d7a214af08bffbca12b853201d5dc66587999b7",
          "md5": "949676c2f0fb9f592fa5709dfbfc315a"
        }
      ]
    }
  ]
}
